services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: medicamentos-app-img
    container_name: medicamentos-app
    # Removido 'user: "${UID}:${GID}"' para evitar conflitos de permissão no deploy
    volumes:
      - ./:/var/www
    networks:
      - medicamentos-network

  web:
    image: nginx:alpine
    container_name: medicamentos-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - medicamentos-network

  db:
    image: mysql:8.0
    container_name: medicamentos-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: medicamentos_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel_user
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - medicamentos-network

networks:
  medicamentos-network:
    driver: bridge

volumes:
  mysqldata:
    driver: local